version: '3' #the version or standards used to write the docker-compose file

services:
    web:
       image: nginx
       ports:
          - 80:80
    database:
       image: mariadb
	   ports:
		  - 3306:3306