version: '3' #the version or standards used to write the docker-compose file

services:
   nginx:
      build: "requirements/nginx/"
      image: nginx
      restart: always
      container_name: nginx
      ports:
         - 443:443
      volumes:
         - wp-volume:/var/www/
      networks:
         - inception
      env_file:
         - .env
   mariadb:
      build: "requirements/mariadb/"
      image: mariadb
      restart: always
      container_name: mariadb
      volumes:
         - mariadb-volume:/var/lib/mysql
      networks:
         - inception
      env_file:
         - .env
   wordpress:
      build: "requirements/wordpress/"
      depends_on:
         - nginx
         - mariadb
         - redis
      image: wordpress
      restart: always
      container_name: wordpress
      volumes:
         - wp-volume:/var/www/
      networks:
         - inception
      env_file:
         - .env
   redis:
      build: "requirements/bonus/redis/"
      image: redis
      restart: always
      container_name: redis
      networks:
         - inception
   ftp:
      build: "requirements/bonus/ftp/"
      image: ftp
      restart: always
      container_name: ftp
      env_file: .env
      ports:
         - '21:21'
         - 10000:10000
      volumes:
         - wp-volume:/home/amouassi/
      networks:
         - inception
   adminer:
      build: "requirements/bonus/adminer/"
      image: adminer
      restart: always
      container_name: adminer
      ports:
         - '5001:5001'
      volumes:
         - wp-volume:/var/www
      depends_on:
         - nginx
         - mariadb
      networks:
         - inception
   site:
      build: "requirements/bonus/site/"
      image: site
      restart: always
      container_name: site
      ports:
         - '30001:30001'
      networks:
         - inception
   influxdb:
      build: "requirements/bonus/influxdb/"
      image: influxdb
      restart: always
      container_name: influxdb
      volumes:
         - influxdb-volume:/usr/local/share/collectd
      depends_on:
         - nginx
         - wordpress
         - mariadb
         - adminer
         - ftp
         - grafana
         - redis
         - site
      networks:
         - inception
   grafana:
      build: "requirements/bonus/grafana/"
      image: grafana
      restart: always
      container_name: grafana
      ports:
         - '3000:3000'
      networks:
         - inception
volumes:
   wp-volume:
      driver_opts:
         type: none
         o: bind
         device: /home/amouassi/data/wp-volume
   mariadb-volume:
      driver_opts:
         type: 'none'
         o: 'bind'
         device: '/home/amouassi/data/mariadb-volume'
   influxdb-volume:
      driver_opts:
         type: 'none'
         o: 'bind'
         device: '/home/amouassi/data/influxdb-volume'

networks:
   inception:
      name: inception
      driver: bridge
